AWSTemplateFormatVersion: '2010-09-09'   
Description: >
    This template deploys two EC2 instances for Bastion servers
Resources:
#Provision EC2 Bastion Instance 0
 EC2Bastion0:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-southeast-2a
      ImageId: ami-942dd1f6
      InstanceType: t2.micro
      IamInstanceProfile: EC2-CF-Read-Write
      NetworkInterfaces: 
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          GroupSet: 
            - Fn::ImportValue: Bastion-SG-ID
          SubnetId:
            Fn::ImportValue: Bastion-Subnet-0-ID
      KeyName: EC2_SSH
      Tags:
      - Key: Name 
        Value: AUSYDPVMBAS0000
      UserData: !Base64 |
             #!/bin/bash
             yum update -y
#Provision EC2 Bastion Instance 1 - Used to create ECS Docker image
 EC2Bastion1:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: ap-southeast-2b
      ImageId: ami-942dd1f6
      InstanceType: t2.micro
      IamInstanceProfile: EC2-CF-Read-Write
      NetworkInterfaces: 
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          GroupSet: 
            - Fn::ImportValue: Bastion-SG-ID
          SubnetId: 
            Fn::ImportValue: Bastion-Subnet-1-ID
      KeyName: EC2_SSH
      Tags:
      - Key: Name 
        Value: AUSYDPVMBAS0001 
      UserData:
        Fn::Base64:
          Fn::Sub:
            - |
              #!/bin/bash
              yum update -y
              yum install -y docker
              service docker start
              usermod -a -G docker ec2-user
              cd /home/ec2-user/
              mkdir ecs-docker-image
              cd ecs-docker-image/
              wget https://s3-ap-southeast-2.amazonaws.com/oliverjamesfletcher-docker/Docker-file
              eval $(aws ecr get-login --region ap-southeast-2 --no-include-email)
              docker build -t ${ECRNameImport}:WordpressBuild000 - < Docker-file
              docker tag ${ECRNameImport}:WordpressBuild000 ${ECRURIImport}:WordpressBuild000
              docker push ${ECRURIImport}:WordpressBuild000
            - 
              ECRNameImport: 
                Fn::ImportValue: ECR-Name
              ECRURIImport: 
                Fn::ImportValue: ECR-URI