AWSTemplateFormatVersion: '2010-09-09'   
Description: >
    This template provisions a CloudCommit repository
Parameters:
#Set Stack name to import values for subnetid
    StackName: 
        Type: String
        Default: CloudFormationTesting004
        Description: Enter CloudFormationTesting004 Stack to import SNS ARN
Resources:        
#CodeCommit Repository
  ECSCodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: ECSCodeCommitRepo
      RepositoryDescription: ECS CodeCommit Repo
      Triggers: 
        - Name: MasterTriggers
          DestinationArn: 
            Fn::ImportValue: !Sub "${StackName}CodeCommitSNSTopicARN"
          Branches: 
          - master
          Events:
          - all