AWSTemplateFormatVersion: '2010-09-09'   
Description: >
    This template provisions a CloudCommit repository
Resources:        
#CodeCommit Repository
  ECSCodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: ECSCodeCommitRepo
      RepositoryDescription: ECS CodeCommit Repo
      Triggers: 
        - Name: MasterTriggers
          DestinationArn: 
            Fn::ImportValue: CodeCommitSNSTopicARN
          Branches: 
          - master
          Events:
          - all
#Export CodeCommit 
Outputs:
  ECSCodeCommitRepo:
    Description: The ID of the CodeCommit Repository
    Value: !Ref ECSCodeCommitRepo
    Export:
      Name: ECS-CodeCommit-Repo-Id