AWSTemplateFormatVersion: 2010-09-09
Description: >
    This template provisions a Elastic Compute Repository
Resources:
#Create Elastic Container Repository
  ECR:
    Type: 'AWS::ECR::Repository'
#Export ECR tag to use in Docker build
Outputs:
  ECRName:
    Value: !Ref ECR
    Export:
      Name: "ECRName"
  ECRARN:
    Value: !GetAtt ECR.Arn
    Export:
      Name: "ECRARN"
  ECRURI:
    Value: !Join [ ".", [ !Ref "AWS::AccountId", "dkr.ecr", !Ref "AWS::Region", !Join [ "/", [ "amazonaws.com", !Ref ECR, ] ] ] ]
    Export:
      Name: "ECRURI"