AWSTemplateFormatVersion: '2010-09-09'   
Description: >
    This template deploys ElastiCache Memcached Cluster
Resources:
  ElastiCacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AZMode: cross-az
      CacheNodeType: cache.t2.micro
      CacheSubnetGroupName: !Ref ElastiCacheSubnetGroup
      Engine: memcached
      NumCacheNodes: 2
      Tags:
        - Key: Name
          Value: AUSYDELASCLUS000
      VpcSecurityGroupIds:
        - Fn::ImportValue: DB-Tier-SG-ID
  ElastiCacheSubnetGroup: 
    Type: AWS::ElastiCache::SubnetGroup
    Properties: 
      Description: ElastiCache Subnet Group for WordPress
      SubnetIds: 
        - Fn::ImportValue: DB-Tier-Subnet-0-ID
        - Fn::ImportValue: DB-Tier-Subnet-1-ID
#Export ElastiCache Cluster Id
Outputs:
  ElastiCacheClusterId:
    Description: The ID of the ElastiCache Cluster
    Value: !Ref ElastiCacheCluster
    Export:
      Name: ElastiCacheClusterId
   ElastiCacheClusterEndpointAddress:
    Value: !GetAtt ElastiCacheCluster.ConfigurationEndpoint.Address
        Export:
      Name: ElastiCacheClusterEndpointAddress