AWSTemplateFormatVersion: '2010-09-09'   
Description: >
    This template deploys Application Load Balancer
Resources:
#Provision ELB ALB
  ApplicationLoadBalancer: 
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets:
        - Fn::ImportValue: App-Tier-Subnet-0-ID
        - Fn::ImportValue: App-Tier-Subnet-1-ID
      LoadBalancerAttributes:
      - Key: idle_timeout.timeout_seconds
        Value: 60
      SecurityGroups: 
        - Fn::ImportValue: ALB-Web-Tier-SG-ID
      Tags:
      - Key: Name
        Value: AUSYDELBALB000
  ApplicationLoadBalancerTG: 
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /healthy.html
      HealthCheckTimeoutSeconds: 5
      Matcher:
        HttpCode: 200
      Name: AUSYDELBALBTG000
      Port: 443
      Protocol: HTTPS
      UnhealthyThresholdCount: 5
      VpcId: !ImportValue VPCId
#Export Application Load Balancer Id
Outputs:
  ApplicationLoadBalancerId:
    Description: The ID of the ApplicationLoadBalancer
    Value: !Ref ApplicationLoadBalancer
    Export:
      Name: ApplicationLoadBalancerId