AWSTemplateFormatVersion: 2010-09-09
Description: >
    This template provisions a RDS Cluster
Parameters:
  DatabaseMasterUsername:
    NoEcho: 'true'
    Description: The WordPress database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DatabaseMasterPassword:
    NoEcho: 'true'
    Description: The WordPress database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.  
Resources:
#Define subnets to be used for RDS Cluster
  RDSClusterSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS Database Subnet Group for WordPress
      SubnetIds: 
        - Fn::ImportValue: DB-Tier-Subnet-0-ID
        - Fn::ImportValue: DB-Tier-Subnet-1-ID
      Tags:
        - Key: Name
          Value: AUYDRDSSUBGR000
#Create RDS Cluster
  RDSCluster:
    Type: AWS::RDS::DBCluster
    DependsOn: RDSClusterSubnetGroup
    Properties:
      BackupRetentionPeriod: "7"
      DatabaseName: AUSYDSQLWP000
      DBSubnetGroupName: !Ref RDSClusterSubnetGroup
      Engine: aurora
      MasterUsername: !Ref DatabaseMasterUsername
      MasterUserPassword: !Ref DatabaseMasterPassword
      Port: "3306"
      Tags:
        - Key: Name
          Value: AUSYDSQLCLUS000
      VpcSecurityGroupIds:
      - Fn::ImportValue: DB-Tier-SG-ID
#Create RDS instance 0
  RDSInstance0: 
    Type: AWS::RDS::DBInstance
    DependsOn: RDSCluster
    Properties:
      DBClusterIdentifier: !Ref RDSCluster
      DBInstanceClass: db.t2.small
      DBSubnetGroupName: !Ref RDSClusterSubnetGroup
      AvailabilityZone: ap-southeast-2a
      Engine: aurora
      Tags:
        - Key: Name
          Value: AUSYDSQLINST000
#Create RDS instance 1
  RDSInstance1:
    Type: AWS::RDS::DBInstance
    DependsOn: RDSCluster
    Properties:
      DBClusterIdentifier: !Ref RDSCluster
      DBInstanceClass: db.t2.small
      DBSubnetGroupName: !Ref RDSClusterSubnetGroup
      AvailabilityZone: ap-southeast-2b
      Engine: aurora
      Tags:
        - Key: Name
          Value: AUSYDSQLINST001
#Export RDS Cluster Endpoint Address 
Outputs:
  RDSClusterEndpointAddress:
    Description: The RDS Cluster Endpoint Address
    Value: !GetAtt RDSCluster.Endpoint.Address
    Export:
      Name: RDS-Cluster-Endpoint-Address